var STYLE_NJ="color: black; background-color: palegreen;"
var STYLE_NEAR="color: black; background-color: aqua;"
var STYLE_FAR="color: white; background-color: orangered;"
var STYLE_ABROAD="color: white; background-color: purple;"

var data=[
    {
        content:"滁州",
        start:"2024-4-5",
        style:STYLE_NEAR,
        tag:["tr:h","tr:m","tr:b","w:ZKY"],
        loc:[{
            name:"滁州",
            altname:"Chuzhou"
        }]
    },
    {
        content:"达摩古洞",
        start:"2024-3-31",
        style:STYLE_NJ,
        tag:["tr:c","w:Family"],
        loc:[{
            name:"南京",
            altname:"Nanjing"
        }]
    },
    {
        content:"上海",
        start:"2024-2-20",
        end:"2024-2-22",
        style:STYLE_NEAR,
        tag:["tr:t","tr:m","tr:b","w:ZKY"],
        loc:[{
            name:"上海",
            altname:"Shanghai"
        }]
    },
    {
        content:"厦门",
        start:"2024-1-22",
        end:"2024-1-27",
        style:STYLE_FAR,
        tag:["tr:p","tr:m","tr:b","w:ZKY"],
        loc:[{
            name:"厦门",
            altname:"Amoy"
        }]
    },
    {
        content:"HHS冬大祭'24",
        start:"2024-1-6",
        end:"2024-1-7",
        style:STYLE_NJ,
        tag:["tr:c","tr:b","w:ZKY","w:HDD","w:XZM"],
        loc:[{
            name:"南京",
            altname:"Nanjing"
        }]
    },
    {
        content:"政治之旅",
        start:"2024-1-3",
        style:STYLE_NJ,
        tag:["tr:m","w:Myself"],
        loc:[{
            name:"南京",
            altname:"Nanjing"
        }]
    },
    {
        content:"花博园之旅",
        start:"2024-1-1",
        style:STYLE_NJ,
        tag:["tr:c","w:Family"],
        loc:[{
            name:"南京",
            altname:"Nanjing"
        }]
    },
    {
        content:"南外新校区探索",
        start:"2023-12-28",
        style:STYLE_NJ,
        tag:["tr:c","w:Family"],
        loc:[{
            name:"南京",
            altname:"Nanjing"
        }]
    },
]